[package]
name = "spirevolt-editor"
version = "0.1.8"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
crossterm = "0.26.1"
unindent = "0.2.1"
terminal_size = "0.2.5"
clearscreen = "2.0.0"
ansi-escapes = "0.1.1"
